# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

name: DaneSpiritGOD.nng.net  # build numbering format
#resources:
  #containers: [ container ]
  #repositories: [ repository ]
#variables: { string: string } | [ variable ]
trigger: 
- master
pr: 
- master
jobs:
  - job: packNugets
    displayName: 'nuget pack and push'
    pool:
      vmImage: 'VS2017-Win2016'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      csprojBuildPlatform: 'AnyCPU'
      buildConfiguration: 'Release'
      srcRoot: './src/'
      nugetSource: 'https://api.nuget.org/v3/index.json'
      nanomsgPlus: 'NanomsgPlus'

    steps:
    - task: DotNetCoreInstaller@0
      inputs:
        packageType: 'sdk' # Options: runtime, sdk
        version: '2.1.500'

    - script: dotnet pack -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) $(srcRoot)$(nanomsgPlus)/$(nanomsgPlus).csproj

    - script: dotnet nuget push $(Build.ArtifactStagingDirectory)\*.nupkg -k $(nuget.key) -s $(nugetSource) -n